---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install MySQL server
  apt:
    name: mysql-server
    state: present

- name: Ensure MySQL is started and enabled
  service:
    name: mysql
    state: started
    enabled: yes

- name: Install Python MySQL library for Ansible
  apt:
    name:
      - python3-pip
    state: present

- name: Install PyMySQL via pip
  pip:
    name: PyMySQL
    executable: pip3

- name: Create EpicBook admin MySQL user
  mysql_user:
    name: epicadmin
    password: "{{ mysql_admin_password }}"
    priv: '*.*:ALL'
    host: localhost
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
